services:
  execution:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./reth-data:/data
      - ./rethlogs:/rethlogs
      - ./jwt.hex:/jwt.hex
    command: >
      ./reth/target/release/reth node
      --chain sepolia
      --datadir /data
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --ws
      --ws.addr 0.0.0.0
      --ws.port 8546
      --metrics 0.0.0.0:9001
      --authrpc.jwtsecret /jwt.hex
      --authrpc.addr 0.0.0.0
      --authrpc.port 8551
    ports:
      - '8545:8545'
      - '8546:8546'
      - '8551:8551'
      - '9001:9001'  # Execution metrics

  consensus:
    image: sigp/lighthouse:latest
    container_name: lighthouse-sepolia
    restart: unless-stopped
    ports:
      - "9000:9000"     # P2P port
      - "5052:5052"     # HTTP API
      - "9100:9100"     # Consensus metrics
    volumes:
      - ./lighthouse-data:/data
      - ./validator_keys:/keys
      - ./jwt.hex:/jwt.hex
    depends_on:
      - execution
    command: >
      lighthouse bn
      --network sepolia
      --datadir /data
      --execution-endpoint http://execution:8551
      --execution-jwt /jwt.hex
      --checkpoint-sync-url https://sepolia.beaconstate.info
      --http
      --http-address 0.0.0.0
      --metrics
      --metrics-address 0.0.0.0
      --metrics-port 9100
      --port 9000

  validator:
    image: sigp/lighthouse:latest
    container_name: lighthouse-validator
    restart: unless-stopped
    ports:
      - "9101:9101"     # Validator metrics
    volumes:
      - ./lighthouse-data:/data
      - ./validator_keys:/keys
    depends_on:
      - consensus
    command: >
      lighthouse vc
      --network sepolia
      --beacon-nodes http://consensus:5052
      --metrics
      --metrics-address 0.0.0.0
      --metrics-port 9101
      --graffiti "Sereé"
      --suggested-fee-recipient 0x0000000000000000000000000000000000000000