services:
  execution:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - execution-data:/data
      - executionlogs:/rethlogs
      - ./jwt.hex:/jwt.hex
    ports:
      - '8545:8545'
      - '8546:8546'
      - '8551:8551'
      - '9001:9001'  # Execution metrics
      - '30303:30303'
      - '30303:30303/udp' #peer discovery
    healthcheck:
      test: >
        /bin/sh -c '
        response=$$(curl -s -X POST -H "Content-Type: application/json" --data "{\"jsonrpc\":\"2.0\",\"method\":\"eth_syncing\",\"params\":[],\"id\":1}" http://localhost:8545) &&
        if echo "$$response" | grep -q "false"; then
          curl -s -X POST -H "Content-Type: application/json" --data "{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":1}" http://localhost:8545 |
          grep -q "0x[0-9a-f]" && exit 0;
        fi &&
        exit 1'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s
    command: >
      ./reth/target/release/reth node
            --chain sepolia
            --datadir /data
            --http
            --http.addr 0.0.0.0
            --http.port 8545
            --ws
            --ws.addr 0.0.0.0
            --ws.port 8546
            --metrics 0.0.0.0:9001
            --authrpc.jwtsecret /jwt.hex
            --authrpc.addr 0.0.0.0
            --authrpc.port 8551
            --port 30303
            --discovery.port 30303
            --max-peers 100
            --bootnodes "enode://92de31edbf700c1ab49065d08fdb7987d5f401798acf10d3b6f929d124106be4426a625fbfa235808b9a61cde8c19b1f8e79ad45adbea0ed57aabf34fce7d588@146.190.13.128:30303,enode://4bd5fa06258212174dec6763e2c307b234c5fca1fe0ab0a8b3e8be5ee825aa22ad0294a49bcfe6c2040eae58084604e937f5b8689314f74f6d29d8920847eee1@146.190.1.103:30303,enode://75ac8f200bb4a111b658857236e0ac5060363d2f91542aabc82b26bf18a4788c86112eeae1cab2838ee4741884daf234c242d7c0e2dbbf706309c3cc3f88ca7d@77.31.232.88:30303"

  consensus:
    image: sigp/lighthouse:latest
    container_name: lighthouse-sepolia
    restart: unless-stopped
    ports:
      - "9000:9000"     # P2P port
      - "5052:5052"     # HTTP API
      - "9100:9100"     # Consensus metrics
    volumes:
      - lighthouse-data:/data
      - ./jwt.hex:/jwt.hex
    depends_on:
      execution:
        condition:
          service_healthy

    command: >
      lighthouse bn
      --network sepolia
      --datadir /data
      --execution-endpoint http://execution:8551
      --execution-jwt /jwt.hex
      --checkpoint-sync-url https://sepolia.beaconstate.info
      --http
      --http-address 0.0.0.0
      --metrics
      --metrics-address 0.0.0.0
      --metrics-port 9100
      --port 9000

  # Observability metrics
  prometheus:
    restart: always
    image: prom/prometheus
    user: root
    depends_on:
      - consensus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheusdata:/prometheusdata
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheusdata'

  grafana:
    restart: always
    image: grafana/grafana
    user: '472'
    depends_on:
      - consensus
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafanadata:/var/lib/grafanadata
      - ./grafana/provisioning/:/etc/grafana/provisioning/


volumes:
  execution-data:
    driver: local
  executionlogs:
    driver: local
  lighthouse-data:
    driver: local
  prometheusdata:
    driver: local
  grafanadata:
    driver: local
